---
- name: Install java and net-tools
  hosts: all
  task:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
    - name: Install java 8
      apt: name=openjdk-8-jre-headless
    
    - name: Install net-tools
      apt: name=net-tools

- name: Download and unpack Nexus installer
  hosts: all
  tasks:
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/