---

- name: deploy jupiter website
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: update ec2 instance
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: install apache server
      yum:
        name: httpd
        state: latest

    - name: change directory to the html directory
      shell: cd /var/www/html

    - name: download web files from github
      get_url:
        url: https://github.com/azeezsalu/jupiter/archive/refs/heads/main.zip
        dest: /var/www/html/

    - name: unzip the zip folder
      ansible.builtin.unarchive:
        src: /var/www/html/main.zip
        dest: /var/www/html
        remote_src: yes

    - name: copy web files from the jupitr-main directory to the
      copy:
        src: /var/www/html/jupiter-main/
        dest: /var/www/html
        remote_src: yes

    - name: remove the jupiter-main directory
      file:
        path: /var/www/html/jupiter-main
        state: absent

    - name: remove the main.zip folder
      file:
        path: /var/www/html/main.zip
        state: absent

    - name: start apache webserver, if not dtarted
      ansible.builtin.service:
        enabled: yes
        name: httpd
        state: started