---
- name: Downloading and installing Jenkins
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: yum update
      yum:
        name: '*'
        state: latest

    - name: add the jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
